ci: prepare the worklow for making commenting reusable

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -1,13 +1,110 @@
-stages:
-  # - build
-  # - deploy
-  # - comment
-  - sync_merge
+.add_comment: &add_comment
+  - |
+    GITLAB_API="https://${CI_SERVER_HOST}:${CI_SERVER_PORT}/api/v4/projects/${PROJECT_ID}/merge_requests/${MR_ID}/notes"
+    AUTH_HEADER="PRIVATE-TOKEN: ${GITLAB_BOT_API_TOKEN}"
 
+    # Get existing comments
+    API_RESPONSE=$(curl --silent --header "$AUTH_HEADER" "$GITLAB_API")
+
+    # Check if the response contains the expected structure
+    COMMENTS=$(echo "$API_RESPONSE" | jq -r ".[] | select(.body | contains(\"$COMMENT_IDENTIFIER\")) | .id")
+
+    # Delete previous preview comments
+    if [ -n "$COMMENTS" ]; then
+      for COMMENT_ID in $COMMENTS; do
+        curl --silent --request DELETE --header "$AUTH_HEADER" "${GITLAB_API}/${COMMENT_ID}"
+      done
+    fi
+
+    # Post a new comment
+    curl --silent --request POST --header "$AUTH_HEADER" --header "Content-Type: application/json" \
+      --data "{\"body\": \"$COMMENT_BODY\"}" "$GITLAB_API"
+
+stages:
+  - build
+  - deploy
+  - comment_preview
+  - sync_merge
+  - comment_github_pr
+
+build_hugo:
+  stage: build
+  image: "${CI_TEMPLATE_REGISTRY_HOST}/pages/hugo/hugo_extended:0.135.0"
+  tags:
+    - build_docs
+  rules:
+    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
+  variables:
+    GIT_SUBMODULE_STRATEGY: recursive
+    NAME: "${CI_COMMIT_REF_SLUG}"
+  script:
+    - hugo --gc --minify --environment staging --baseURL "${DOCS_PREVIEW_URL_BASE}/${NAME}"
+    # use branch name like directory name for the URL path going forward
+    - mv -v public "${NAME}"
+    - tar -czf archive.tar.gz "${NAME}"
+  artifacts:
+    paths:
+      - archive.tar.gz
+    expire_in: 1 week
+
+deploy_preview_hugo:
+  stage: deploy
+  image: espressif/scp
+  tags:
+    - deploy_docs
+    - shiny
+  rules:
+    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
+  needs: ["build_hugo"]
+  variables:
+    SSH_KEY: "$DOCS_PREVIEW_PRIVATEKEY" # SSH_KEY used inside espressif/scp
+    SERVER_PATH: "$DOCS_PREVIEW_PATH"
+    SERVER_URL_BASE: "$DOCS_PREVIEW_URL_BASE"
+    USER: "$DOCS_PREVIEW_SERVER_USER"
+    SERVER: "$DOCS_PREVIEW_SERVER"
+    NAME: "${CI_COMMIT_REF_SLUG}"
+  script:
+    # upload and extract the archive,
+    # delete the old directory with the same name (if doesn't contain . or /)
+    # so as not to accumulate garbage from the previous run
+    - cat archive.tar.gz | ssh ${USER}@${SERVER}
+        "cd ${SERVER_PATH};
+        [[ \"$NAME\" != *.* && \"$NAME\" != */* ]] && [ -d \"$NAME\" ] && rm -rf \"$NAME\";
+        pwd; tar xzvf -"
+    - echo "Preview ${SERVER_URL_BASE}/${NAME}"
+
+post_preview_link:
+  stage: comment_preview
+  image: badouralix/curl-jq
+  tags:
+    - deploy_docs
+    - shiny
+  rules:
+    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
+  needs: ["deploy_preview_hugo"]
+  variables:
+    SERVER_URL_BASE: "$DOCS_PREVIEW_URL_BASE"
+    NAME: "${CI_COMMIT_REF_SLUG}"
+    MR_ID: "$CI_MERGE_REQUEST_IID"
+    PROJECT_ID: "$CI_MERGE_REQUEST_PROJECT_ID"
+  script:
+    - |
+      # Create varialbes for adding a comment
+      COMMENT_IDENTIFIER="🎉 Preview for this MR"
+
+      PREVIEW_LINK="${SERVER_URL_BASE}/${NAME}"
+      COMMENT_BODY="🎉 Preview for this MR: ${PREVIEW_LINK}"
+
+    # Reuse the script block
+    - *add_comment
+
+# Todo
+#- If triggered manually, run only these steps
+#- Try Ubuntu instead of Dabian
+#- Try creating a new PR
 # After testing:
 #- Replace f-hollow with espressif
 #- Replace enhancement with GitLab-Sync-Merge
-#- Figure out which GitHub token to use
 sync_merge_to_github:
   stage: sync_merge
   image: debian:latest
@@ -44,120 +141,70 @@ sync_merge_to_github:
     # Create a PR on GitHub
     - export GITHUB_TOKEN="$GITHUB_ACCESS_TOKEN"
     - |
-      if gh pr list --repo "$GITHUB_REPO" --head "$SOURCE_BRANCH" | grep -q "$SOURCE_BRANCH"; then
-        echo "PR already exists. Skipping..."
+      PR_URL=$(gh pr list --repo "$GITHUB_REPO" --head "$SOURCE_BRANCH" --json url -q '.[0].url')
+
+      if [[ -n "$PR_URL" ]]; then
+        PR_NUMBER=$(gh pr view "$PR_URL" --json number -q '.number')
+        echo "PR already exists: #$PR_NUMBER"
+        echo "**GitHub PR:** $PR_URL"
       else
-        gh pr create \
+        PR_URL=$(gh pr create \
           --repo "$GITHUB_REPO" \
           --head "$SOURCE_BRANCH" \
           --base main \
           --title "Sync Merge: ${SOURCE_BRANCH}" \
-          --body "This PR syncs the GitLab branch ${SOURCE_BRANCH} to GitHub." \
-          --label "enhancement"
-        echo "PR created successfully with label 'GitLab-Sync-Merge'."
+          --body "This PR syncs the GitLab branch ${SOURCE_BRANCH} to GitHub.\n\nThe changes have been reviewed internally." \
+          --label "enhancement" \
+          --json url -q '.url')
+
+        if [[ -n "$PR_URL" ]]; then
+          PR_NUMBER=$(gh pr view "$PR_URL" --json number -q '.number')
+          echo "PR created successfully: #$PR_NUMBER"
+          echo "**GitHub PR:** $PR_URL"
+        else
+          echo "Failed to create PR."
+          exit 1
+        fi
       fi
 
-    # - |
-    #     if gh pr create \
-    #       --repo "$GITHUB_REPO" \
-    #       --head "$SOURCE_BRANCH" \
-    #       --base main \
-    #       --title "Sync Merge: ${SOURCE_BRANCH}" \
-    #       --body "This PR syncs the GitLab branch ${SOURCE_BRANCH} to GitHub." \
-    #       --label "enhancement"
-    #     then
-    #       echo "PR created successfully with label 'GitLab-Sync-Merge'."
-    #     else
-    #       echo "PR already exists or another error occurred. Skipping..."
-    #     fi
+    # Store PR_NUMBER and PR_URL as artifacts
+    - cd $CI_PROJECT_DIR
+    - echo "PR_NUMBER=$PR_NUMBER" > pr_info.txt
+    - echo "PR_URL=$PR_URL" >> pr_info.txt
 
-# build_hugo:
-#   stage: build
-#   image: "${CI_TEMPLATE_REGISTRY_HOST}/pages/hugo/hugo_extended:0.135.0"
-#   tags:
-#     - build_docs
-#   rules:
-#     - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
-#   variables:
-#     GIT_SUBMODULE_STRATEGY: recursive
-#     NAME: "${CI_COMMIT_REF_SLUG}"
-#   script:
-#     - hugo --gc --minify --environment staging --baseURL "${DOCS_PREVIEW_URL_BASE}/${NAME}"
-#     # use branch name like directory name for the URL path going forward
-#     - mv -v public "${NAME}"
-#     - tar -czf archive.tar.gz "${NAME}"
-#   artifacts:
-#     paths:
-#       - archive.tar.gz
-#     expire_in: 1 week
+  artifacts:
+    paths:
+      - pr_info.txt
+    expire_in: 1 hour
 
-# deploy_preview_hugo:
-#   stage: deploy
-#   image: espressif/scp
-#   tags:
-#     - deploy_docs
-#     - shiny
-#   rules:
-#     - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
-#   needs: ["build_hugo"]
-#   variables:
-#     SSH_KEY: "$DOCS_PREVIEW_PRIVATEKEY" # SSH_KEY used inside espressif/scp
-#     SERVER_PATH: "$DOCS_PREVIEW_PATH"
-#     SERVER_URL_BASE: "$DOCS_PREVIEW_URL_BASE"
-#     USER: "$DOCS_PREVIEW_SERVER_USER"
-#     SERVER: "$DOCS_PREVIEW_SERVER"
-#     NAME: "${CI_COMMIT_REF_SLUG}"
-#   script:
-#     # upload and extract the archive,
-#     # delete the old directory with the same name (if doesn't contain . or /)
-#     # so as not to accumulate garbage from the previous run
-#     - cat archive.tar.gz | ssh ${USER}@${SERVER}
-#         "cd ${SERVER_PATH};
-#         [[ \"$NAME\" != *.* && \"$NAME\" != */* ]] && [ -d \"$NAME\" ] && rm -rf \"$NAME\";
-#         pwd; tar xzvf -"
-#     - echo "Preview ${SERVER_URL_BASE}/${NAME}"
+sync_merge_comment:
+  stage: comment_github_pr
+  image: badouralix/curl-jq
+  tags:
+    - deploy_docs
+    - shiny
+  rules:
+    - if: '$CI_MERGE_REQUEST_LABELS =~ /GitHub-Sync-Merge/'
+  needs:
+    - sync_merge_to_github
+  variables:
+    SERVER_URL_BASE: "$DOCS_PREVIEW_URL_BASE"
+    NAME: "${CI_COMMIT_REF_SLUG}"
+    MR_ID: "$CI_MERGE_REQUEST_IID"
+    PROJECT_ID: "$CI_MERGE_REQUEST_PROJECT_ID"
+  script:
+    - |
+      # Load PR_NUMBER and PR_URL from artifact file
+      if [ -f "pr_info.txt" ]; then
+        source pr_info.txt
+      else
+        echo "pr_info.txt not found!"
+        exit 1
+      fi
 
-# post_preview_link:
-#   stage: comment
-#   image: badouralix/curl-jq
-#   tags:
-#     - deploy_docs
-#     - shiny
-#   rules:
-#     - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
-#   needs: ["deploy_preview_hugo"]
-#   variables:
-#     SERVER_URL_BASE: "$DOCS_PREVIEW_URL_BASE"
-#     NAME: "${CI_COMMIT_REF_SLUG}"
-#     MR_ID: "$CI_MERGE_REQUEST_IID"
-#     PROJECT_ID: "$CI_MERGE_REQUEST_PROJECT_ID"
-#   script:
-#     - |
-#       # Print MR_ID and PROJECT_ID for debugging
-#       echo "MR_ID: ${MR_ID}"
-#       echo "PROJECT_ID: ${PROJECT_ID}"
-#       echo "$CI_SERVER_HOST"
-#       echo "${CI_SERVER_PORT}"
+      # Create varialbes for adding a comment
+      COMMENT_IDENTIFIER="🚀 GitHub PR"
+      COMMENT_BODY="🚀 GitHub PR for sync-merging: [#$PR_NUMBER]($PR_URL)"
 
-#       GITLAB_API="https://${CI_SERVER_HOST}:${CI_SERVER_PORT}/api/v4/projects/${PROJECT_ID}/merge_requests/${MR_ID}/notes"
-#       AUTH_HEADER="PRIVATE-TOKEN: ${GITLAB_BOT_API_TOKEN}"
-
-#       # Get existing comments
-#       API_RESPONSE=$(curl --silent --header "$AUTH_HEADER" "$GITLAB_API")
-#       echo "API Response: $API_RESPONSE"  # Add this line for debugging
-
-#       # Check if the response contains the expected structure
-#       COMMENTS=$(echo "$API_RESPONSE" | jq -r '.[] | select(.body | contains("🎉 Preview for this MR")) | .id')
-
-#       # Delete previous preview comments
-#       if [ -n "$COMMENTS" ]; then
-#         for COMMENT_ID in $COMMENTS; do
-#           curl --silent --request DELETE --header "$AUTH_HEADER" "${GITLAB_API}/${COMMENT_ID}"
-#         done
-#       fi
-
-#       # Post new preview link
-#       PREVIEW_LINK="${SERVER_URL_BASE}/${NAME}"
-#       COMMENT_BODY="🎉 Preview for this MR: ${PREVIEW_LINK}"
-#       curl --silent --request POST --header "$AUTH_HEADER" --header "Content-Type: application/json" \
-#         --data "{\"body\": \"${COMMENT_BODY}\"}" "$GITLAB_API"
+    # Reuse the script block
+    - *add_comment
